"""Cross-implementation conformance.

The corpus in `spec/test-vectors-v1` was generated by the Python reference, so on its own it
proves self-consistency and nothing more. These tests run a SECOND implementation over the
same vectors and require identical verdicts.

Any disagreement here is a specification defect first and an implementation bug second. The
correct response to a failure is to work out which reading the specification actually
licenses and fix the document, not to tune whichever implementation is louder.

The Go verifier is skipped when it has not been built, so the suite still runs on a machine
without a Go toolchain:

    cd impl/go && go build -o scpe-verify.exe .
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
VECTORS = REPO / "spec" / "test-vectors-v1"
PY_VERIFIER = REPO / "reference" / "scpe_verify.py"
GO_VERIFIER = REPO / "impl" / "go" / ("scpe-verify.exe" if sys.platform == "win32"
                                      else "scpe-verify")

VECTOR_DIRS = sorted(p for p in VECTORS.iterdir()
                     if p.is_dir() and (p / "expected.json").is_file())

needs_go = pytest.mark.skipif(
    not GO_VERIFIER.is_file(),
    reason="Go verifier not built; run `cd impl/go && go build -o scpe-verify.exe .`")


def run_python(vector: Path) -> dict:
    proc = subprocess.run(
        [sys.executable, str(PY_VERIFIER), str(vector / "artifact.bin"),
         "--policy", str(vector / "allowed_signers"), "--json"],
        capture_output=True, text=True, timeout=180)
    return json.loads(proc.stdout)


def run_go(vector: Path) -> dict:
    proc = subprocess.run(
        [str(GO_VERIFIER), str(vector / "artifact.bin"),
         "--policy", str(vector / "allowed_signers"), "--json"],
        capture_output=True, text=True, timeout=180)
    assert proc.stdout.strip(), f"go verifier produced no JSON; stderr:\n{proc.stderr[-800:]}"
    result = json.loads(proc.stdout)
    assert result["exit"] == proc.returncode, "exit code must match the reported status"
    return result


@needs_go
@pytest.mark.parametrize("vector", VECTOR_DIRS, ids=lambda p: p.name)
def test_go_matches_the_recorded_expectation(vector):
    expected = json.loads((vector / "expected.json").read_text())
    got = run_go(vector)
    assert got["status"] == expected["status"]
    assert got["exit"] == expected["exit"]
    for name, value in (expected.get("facets") or {}).items():
        assert got["facets"].get(name) == value, f"facet {name}"


@needs_go
@pytest.mark.parametrize("vector", VECTOR_DIRS, ids=lambda p: p.name)
def test_the_two_implementations_agree(vector):
    """Identical bytes must yield an identical verdict everywhere. This is the property the
    whole design protects, and it is the one a single implementation cannot demonstrate."""
    go, py = run_go(vector), run_python(vector)
    assert go["status"] == py["status"], f"status: go={go['status']} python={py['status']}"
    assert go["exit"] == py["exit"]
    assert (go.get("facets") or {}) == (py.get("facets") or {})


@needs_go
def test_a_passing_result_names_its_limits_in_both(tmp_path):
    """§11.4 is not decoration: an implementation that drops `not_checked` on a pass has
    removed the honesty mechanism while still returning `ok`."""
    passing = [v for v in VECTOR_DIRS
               if json.loads((v / "expected.json").read_text())["status"] == "ok"]
    assert passing, "corpus has no passing vector"
    for vector in passing:
        assert run_go(vector)["not_checked"], f"{vector.name}: go dropped not_checked"
        assert run_python(vector)["not_checked"], f"{vector.name}: python dropped not_checked"


@needs_go
def test_the_duplicate_key_rule_survives_a_second_language():
    """The reason §4.7 is written down.

    Go's `encoding/json`, Rust's `serde_json`, JavaScript and Python's own default loader
    all accept a duplicate object key with last-wins. Only deliberate code refuses it. The
    `signed-duplicate-key` vector carries a VALID signature over a payload that declares
    both `digitalCapture` and `trainedAlgorithmicData`, so an implementation that takes the
    default path reports whichever origin the signer ordered last.

    If this test ever passes trivially — because someone made the vector easier rather than
    the parser stricter — the corpus has stopped testing the only rule that needs two
    languages to test at all.
    """
    vector = VECTORS / "signed-duplicate-key"
    assert vector.is_dir(), "the signed-duplicate-key vector is missing"
    for name, result in (("go", run_go(vector)), ("python", run_python(vector))):
        assert result["status"] == "malformed-input", f"{name} accepted a duplicate key"
        assert "duplicate" in result["detail"].lower(), f"{name} refused for the wrong reason"
